apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: anubis
  labels:
    app.kubernetes.io/name: anubis
    app.kubernetes.io/component: app
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: anubis
      app.kubernetes.io/component: app
  template:
    metadata:
      name: anubis
      labels:
        app.kubernetes.io/name: anubis
        app.kubernetes.io/component: app
    spec:
      volumes:
        - name: app-config
          secret:
            secretName: app-config
      containers:
        - name: anubis
          image: ghcr.io/techarohq/anubis:v1.28.1
          envFrom:
            - secretRef:
                name: app-envs
          env:
            - name: "BIND"
              value: ":80"
            - name: "METRICS_BIND"
              value: ":9090"
            - name: "TARGET"
              value: " "
            - name: "REDIRECT_DOMAINS"
              value: "*.hyvel.eu"
            - name: "COOKIE_DOMAIN"
              value: "hyvel.eu"
            - name: "POLICY_FNAME"
              value: "/data/cfg/botPolicy.yaml"
            - name: "SERVE_ROBOTS_TXT"
              value: "true"
            - name: "DIFFICULTY"
              value: "4"
          volumeMounts:
            - name: app-config
              mountPath: "/data/cfg/botPolicy.yaml"
              subPath: botPolicy.yaml
              readOnly: true

          startupProbe:
            httpGet:
              path: /healthz
              port: 9090
              scheme: HTTP
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 12
            
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9090
              scheme: HTTP
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9090
              scheme: HTTP
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
