apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - backup-schedule-app.yaml
  - secret-app.yaml
  - secret-db.yaml
  - pvc-db.yaml
  - deploy-db.yaml
  - service-db.yaml
  - deploy-app.yaml
  - service-app.yaml
  - ingress-app.yaml
