apiVersion: v1
kind: Secret
metadata:
    name: db
    namespace: lldap
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:MOs7oUrQ+nFIqT5Op0naBmRjFw94FMjHv5cpyxMO,iv:V5ME3UwTpCuKfCXY+uPzScHQzsuv/rzt+5iNoa71kiQ=,tag:My2vq432Pml0mBlfhdXokA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLcE9QWVBHYWd1Y1dnb0Y4
            VFpOajdoOVJPOFltWHRuUmxCRVhxMjQyTUNvClY1Wnp0UUdQdEZtMVg0Nml3UVgv
            cGh0L2xFbU90bWc0anAzU0NPbk5RbnMKLS0tIFlJaW5lbnVFR0k2cnMrQ0U2TllN
            L01JVE1FdTBKQUdMV1Q1aHI1VEZXQ0UKNQzlG8Jbq9llghBZe/TSbZg9OoM3wLqM
            aigAd6nl2XSLCUzgd/+HphZorSJq2baO7vrWaUxG4ddqjHwelvt+Kg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1na9sc4yaxzdvt5jqpq99q3umg2qkhsv3use7lgej6lw46wz8sgrspg7a2h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-23T06:00:05Z"
    mac: ENC[AES256_GCM,data:svuV0WX4QZ8jKVOp2pME354e0aYszzeBTeL1wJPYMnU4QqG0TfBOgUFgL4UDvSI/K0EnEWZNiFDhbNgwHRVFvSZpI7CTuhQKG+2EE0aXxWVg1VcQI0Owp+wJyBOPnpfUsHFmqCSyltEyhBvBi16c62CF+yx2Z71oqwuI3uA7NqI=,iv:cVjOzsXOgzC3cnUu/7gN2tKGhzFkMK9tYj+kHg4PDis=,tag:VJeF1yy6ffKX5FnSpA6bMg==,type:str]
    version: 3.13.1
