apiVersion: v1
kind: Secret
metadata:
    name: app
    namespace: lldap
stringData:
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:3yxAAdxInRGh3y/0SotnAf5CvMrCU9J+qMnCQlDDtCXbHLiUqZfyd0ZmvjvuI0MBYI1+TWb0jjojypzrw/VYsK5/3oaRDm8rIznxox6vh5KjYzLe0kMedYd+SD5Xag6wz3d1/mKl+u+Xy7wI4kCi+ouLMxQ6ws3fUj3lR0zGXIg=,iv:MbpUWe5Gjsh3M8qEh4oSFtiaTvcRuWlAk/32RZcGLdY=,tag:s9HNDROtPKYZPgsQYK+MQQ==,type:str]
    LLDAP_KEY_SEED: ENC[AES256_GCM,data:NVvRS5TJC/yYZQLFYRnx/EQ1QAsyXxdWRsdv791IOUCkH0kCY6zim+rqNZHBEEsz85vcA2+5ghngDR/mKx7QO7HfT3TjtBuBoYXW5rOYg+wzDNWuwDkYdj3pKTjdGqaBvL15O2hlX4pH+l2YY6NTTEFh0H2g9qKR+yxhPuHhj9w=,iv:vux4G68oeOliLB36+6vpHwMglAk8XduBObKxtWeWp40=,tag:6CwwyT0onIgruxtzUeHHPg==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:TilXUKkQvbPsVs6u76OSDL0dLeTk1V94OX4SKDuijcQ=,iv:RLRT2NB8oiiitm34zwAHIPw46g8DAV3jN8+WTrzvxdc=,tag:Z9CipreB6ntKJ4REtEtqVA==,type:str]
    LLDAP_DATABASE_URL: ENC[AES256_GCM,data:o5GhUZZk0/rdJwFPVqFzVN3+A+KRcIVSAlPO70/TPxDYIZKIqtRxAmRXJyFgbFViKlorGQ==,iv:QPn3QOLUK2qRBGC288HdvM9Vaddbo4ldOQZQGRjqfnQ=,tag:wmFTzJUscDJY3dLKxT8/mw==,type:str]
    LLDAP_SMTP_OPTIONS__SERVER: ENC[AES256_GCM,data:5hUQoBVoc2ubtUIA5q0=,iv:MVRD2i6bP5froTMjzeI5R1hVP4sGNiaFv5VfvXzIaIo=,tag:bAMF+jVQ8j60rkjo/ZUwfQ==,type:str]
    LLDAP_SMTP_OPTIONS__USER: ENC[AES256_GCM,data:YJHogVwtdIq7ydyaseCpS2LA,iv:+kf3PnvcGmIP9SNboHLJ/BQo9B+GZu0hlbNCwbXGoa4=,tag:5WK5moWbgT/Lk6UGcHdWVQ==,type:str]
    LLDAP_SMTP_OPTIONS__PASSWORD: ENC[AES256_GCM,data:Yia7LChLRr5WYhhRjWXn0t4isg==,iv:WL8YF2XoippMfmJV0ukEUTvG24rjEnnyUtIbXRE4auk=,tag:lyF48q+bwICfzXQiH5zudQ==,type:str]
    LLDAP_SMTP_OPTIONS__FROM: ENC[AES256_GCM,data:KrByKMKH/l9GSLMerr0quf8+c931ZCIvE/05MmNcPDU=,iv:lwAqQIbh9U/Z13L9yj9pgm73c8wkVvtv8wI7aaKIVA8=,tag:Sx2c1tWC3saTweuIC/ly5Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZE0zV0luOXJHajRuRWU1
            L0RTNDBVSVZEVWxTcERBcTlzZXhGa3h0b21nCmxLaHpyZFFHLzd6amJKWmh6cGE0
            OG9Ta3JNekJWbzQvS1FTcmpLdlh3SnMKLS0tIHFRZ1duZ1NVSTRmWlRFbUhkV2FX
            VTQ3QzFITTRza2FzdEpEcUc5THBwVDQKLAQV8YHHc/24X072wjtCF+R0jNRjjlly
            aFFCScEhXeoznNIVxHRrssFFCDTyZ30PTBXIq/6IrUQY7ljdFTI8zg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1na9sc4yaxzdvt5jqpq99q3umg2qkhsv3use7lgej6lw46wz8sgrspg7a2h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-23T06:00:01Z"
    mac: ENC[AES256_GCM,data:NzwL7A9IkJ5ro5foWf2vNv8dP+TBh9G+HcPjAnju6IP/kz/3xIAgHZh3wtJKj/qMZx3ec5Tk4jyqHksXgWeEgKgIE86rt+nBZ82wddl2RwgpVVthcLR7K07uYQyImYIP26DFF4NEvL7sNcxGCdLKlxA+bATWepA5ZCmRGF1Ep+I=,iv:082gsAtB+4rOGlepYK0AIRGdhUOuJmDWbdOVl5LdjAs=,tag:5cZ5LBkfRMhJI/F+ZJuzdA==,type:str]
    version: 3.13.1
