apiVersion: v1
kind: Secret
metadata:
    name: nginx
    namespace: hyvel
stringData:
    nginx.conf: ENC[AES256_GCM,data:nRwZm4iIG7YEjmzoPwrTQDhbH4GhsXugqlkNhzp2nJX2hO59xodTTtNNULdl3i05FqJprujLTg2kvESQfCQQ85XisveOicXztWkq/kIVJ7mO9XU5aYAmQtjlIz+Xwo6X5uAMVNk4+TkHYYxyaTifj7380qoRkgEEV5w9d94bedj0A3bpCmbgLgAZcba4LLRO/1nd3TD2v5JiKi5GPfDU/MmE4/fS00UHyfheKIsCIdu2jpgutkM8L4BNv2LaALIHY2t1Se0lA0hboIStuG75oHsgTx8vbXIIONo1wZZFFXsYe1dXP081UW8LtkAk9r1ILSYfUqz2OkazJ2pELtyY1an/gLabdnsK54iTX3nkKP5eYnNoU2SsE+s8IzSulJ/yrmkLaVVMkz/lD8gnqVY5af08hLA6SvztoAMEKlGQ1C2o2SCEaSbrrUzdwIc5o+QKeedgo4oGmeflYX1/H/3CrKJPJDCSr7HNheM4W1GN5z0AoWqc2uyCAQuh10U06RKLNYRvwKm1BjZvIYRyOBDEn1XcwbpzVsg79PdVRCV48ygdWj9ndX91kBAYrtVPwLwjdBAlQdRdtiukrFq+fFxz8iu1PdHSsvOSbXbiPlmnxn01Xe1PP8GxbVMOb60rihwhsA72TA8cPA4kIakMyC00ETof8WbMd6RF1JdBonicwyRApOswhos3RoJbl1h53K4ic98qUv9uYSuzFc+l3doljxU4w6wj2z/74DxtDHK8maLc6e0tIJZpWQNkzsGgzAxgDVvx8CMNMAzkiuhL569YqALR0jdHVzWxUXEAEqjh/qMek6gGm/446mKGpFSEoBGW3Y1hblLQLB9R2ISEc3GBwz8uML3L//OpVg+OjHMaEkx578neBCJfw6sTxz7yDabubxXVDj0TvG3LhZQGF5CBclRYLk+b3kchYBjcbhV+mDcZgi1hx4Dgo5F6m6M+B2oEEQ75SP6UID6A0OIoqTkw4u3fZ8Ou8LGYQuLUD5CDagU=,iv:QjagfcPBTY35GhmG9rtQJosaYZTAQyaylpI17tU8qeQ=,tag:MoDh98kBYp+Yy8xhqSUzOw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUTG5ZZHN5Zk1COW5YR29p
            NkI1NDVjclZnZmtNUS9oM2dTckZPbmQ0ckRRCmcvOVd1WUV2Q2MyZ1ZEV1d0Q25I
            TUZBTUxVaHVlL00xdlEyNE9jZGlLTlUKLS0tIDN2bkNZNXNlU1hxYW5zZWozUXdB
            TWlzRVY5WFlQUXk5dmVzQ0lrTFFybjQKKOriFZA0xIrbGw48TIw2rwAWlak76GqV
            cV0i3X1hEI3Ve4BMJg3H8A7j2T6x9KeYXGCUA4b0BpPxgCwV6FOaTQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1na9sc4yaxzdvt5jqpq99q3umg2qkhsv3use7lgej6lw46wz8sgrspg7a2h
    encrypted_regex: ^(data|stringData|email|token_id|token_secret|client-certificate-data|client-key-data|certificate-authority-data)$
    lastmodified: "2026-07-30T15:41:56Z"
    mac: ENC[AES256_GCM,data:o8qyFsEGu8K46tys99NDvz/j7RlBYz8kST/uJ1sArXeXXgjZ6FdTkqg4+5fBw5EphGFaofbOrXPL1BRHVaykXc9jyF8VTI7CeAXJGZhvx3P6qPP5XcIqKta/cZnlCp1ppCjtserOJPQKm8XrzSnnw2pVsaygnBLRte5qpg1yDDA=,iv:X6gHrmQgIN/hjz4in19X9sFH/DtzLBcnIsh2w4pYQVE=,tag:MIHAzLwBLBhDl0tLRBK9uQ==,type:str]
    version: 3.13.1
