apiVersion: v1
kind: Secret
metadata:
    name: nginx
    namespace: hyvel
stringData:
    nginx.conf: ENC[AES256_GCM,data:zmm7zY0FDcDqjcNnJ31xIkVcAPFHgeIrOThW/GljGUeyY1ukI053o3nTb3JspbNxvwtldwF0c1EQRABZmzjmieQTOaVwe+2bW84tH0ps2RkGE8yizjSZVJ9ifVl0ySYdE6s3p9QPIl7u2Oam/IvW+oxsIcGiffZnwb9SdXz5xKne/t93oMGELAFWeSegY9dfGsYMEenwVI7Ue3D0+KFaIt+RtVUiW4R+BJu7NXOzCEbtxYyvjYP62jyLlsaYDt4tU0fSclFPwOecJ6HsfgcmgCC6Hl4KVVXtwfEcmS73DJycW6zo7ys+rKvuhiWC9nAklecb7C5LJT7JP56VWrcYPPgZ2PzRCN6Z9svD9094mKUDXh0j1sPq+jvMEC4WhCqke6/r7urY2bpvph0Vb6G2rqGJdSGTCzcl/yjw5oux7mzG0JCKQ3lHyukl0eDp++Qw1chESCMTShfUhw3kr+104Tr8hpGldqF1Et56cuEd4VzhD7vYnHEJZQjp1wo21IYjaxxk7hddJjlRxOmoU5RdLtTlr04LFnq8zCaA0roNIWgIJQgdLMH8wxjb0Tjmdk7x4agCVIkyNToJ9TtipGsjM6QX6m+rWxpH4HO7g0ZgoFZA+8+ipleV+N2poAF4G28OYC7PXV7TGatNNlzEEuvCmSGHo2NiKFdQwoBAPMlWqiE04Xq6G2oJg4AyfV9NLiIpM0VRCtndyTuxGzZ8Av7tZZweYsKmXiQBXRcyhmTR0yFNspOCaReBF3SOrTozBBfAoL9K8aLIuwUcgoF2ZcLYk2a37cCp27E9hPb8kTIrG3IJ15+WyUmqG9UTvmF3Q2dhXo8kqvVaZZm/V4+1gbr0057+wOat7Hr8k+Kb/zeHl36NZfOPbPVFFFx5SGZLEa8tj3DAWJ2nEz3kb15geL8noLGMvGygrGa0qIFwv4o6pXpviinMfZcQ5ia+ntILsWhJwvXGyL45knHyxWw/i4/raZL6WEAZaNy5kxKn9LW/ZObTExNfxj/k0gbhKOmnliy1Df+LxbY=,iv:Crqj4u5J/zaIf0EQWaUhrKmXeCwZENEoxNk2SLUgnsE=,tag:eaKMEr4Vwi4hshA/mDfK2A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUTG5ZZHN5Zk1COW5YR29p
            NkI1NDVjclZnZmtNUS9oM2dTckZPbmQ0ckRRCmcvOVd1WUV2Q2MyZ1ZEV1d0Q25I
            TUZBTUxVaHVlL00xdlEyNE9jZGlLTlUKLS0tIDN2bkNZNXNlU1hxYW5zZWozUXdB
            TWlzRVY5WFlQUXk5dmVzQ0lrTFFybjQKKOriFZA0xIrbGw48TIw2rwAWlak76GqV
            cV0i3X1hEI3Ve4BMJg3H8A7j2T6x9KeYXGCUA4b0BpPxgCwV6FOaTQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1na9sc4yaxzdvt5jqpq99q3umg2qkhsv3use7lgej6lw46wz8sgrspg7a2h
    encrypted_regex: ^(data|stringData|email|token_id|token_secret|client-certificate-data|client-key-data|certificate-authority-data)$
    lastmodified: "2026-07-29T07:53:32Z"
    mac: ENC[AES256_GCM,data:gMEyZlApDaTr1VavlYpwk3k2UiBTUgJ3Krn81m8Lf9doBlFORO8G1TXbnZDsK2Qzih3KMkL7BYH9hfm5rbw9KIhNCwtKmfReVaFRY3f+PK+9uFpesdmKCa3GAlDo+pZhLDcYerwsPN2geByOeM8KV5A4Ca2iUtPE7Ns6607ZVks=,iv:uzgJyTPgB1zU1o2wpcMGKHZouEBTD6c4jMPkmP1BM3Q=,tag:KOpF5Zjdm68VNahbbA1PIw==,type:str]
    version: 3.13.1
