apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app
  namespace: matrix
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-data-sc-0
  resources:
    requests:
      storage: 10Gi