apiVersion: v1
kind: Secret
metadata:
  name: hyvel-dns01-token
  namespace: cert-manager
stringData:
  api-key: ENC[AES256_GCM,data:ipCULGWcYsbjOrvHt66rskM+jcM9PArxjsMtRHn2hjfN5hOsB2Hwd2FxAIrqmrDvAuiAE1jGdhmCbRWjmqMSdS/cHzs=,iv:fsZyaoc37u64HI1fnh75ZVWO0j9mSA3fXYfoOJ3xNFo=,tag:NfVNw1FBOLFNeJhtTb/OQg==,type:str]
  secret-key: ENC[AES256_GCM,data:wSPR8lppOdzIc47/S/yLk4Lm3is8r8AJqgFNkSw4RYKpxnbij5MBfAE3feVv3/pGCTmS+WqQp1BXTGmB6/7DC1/A24k=,iv:kEjp+msPAHmqxlQ1wCZpRkOmA0znph5RO9C7Rtct6AA=,tag:dk28+zJmRdq2npdjDLyp1w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPK2ZsQU5leUpMZEtTaFVB
        Zkl1ZzUyUXpndVB5eisvRm5lMHEySnJ6d240CnNacUlSQksvMGZhSHdHdTUvT21R
        VHdObFZ3T0hXaVM4QUhObDBnV085OVUKLS0tIEZXYkxEV0FjR0tHZUY0NFBuUEtX
        dFZaSnRjSjhrY09vZ3hzRG9LTnkxNmcK4Xwv1FsBmxntFE3RnaphrbRbWHrA7qR8
        CE1Q8OBfQu7InHY/l37uUrUe1wkpVuiMOc7etZGK/1S9DVHcIYpnIQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1na9sc4yaxzdvt5jqpq99q3umg2qkhsv3use7lgej6lw46wz8sgrspg7a2h
  encrypted_regex: ^(data|stringData|email)$
  lastmodified: "2026-05-25T10:35:27Z"
  mac: ENC[AES256_GCM,data:zK3MFJoV8T1lWI6mgZw8sgGRR+gYnkqH9UmAwsm1P8MNTNw4El9JeD37y0Z2jnNTpf9xSm9CI+lZ20NVWdaLR8mABF373AhET+iKR/9dj2qs5Hfm4jleRfwQJn2P5bQ4tqX8KyFSg2TSptmMKMjnnnyaiiYyQOe00vrmJy+fvjU=,iv:jIk+v0I9l6jYqyCsQya8/mUxsDkZS79JImM8DegcXXQ=,tag:p4rUNmehVetQzLhFKDrKBg==,type:str]
  version: 3.13.1
