apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: xui
  labels:
    app.kubernetes.io/name: xui
    app.kubernetes.io/component: app
spec:
  selector:
    app.kubernetes.io/name: xui
    app.kubernetes.io/component: app
  ports:
    - port: 7700
      protocol: TCP
    - port: 7560
      protocol: TCP
    - port: 7554
      protocol: TCP
    - port: 7555
      protocol: TCP
    - port: 7556
      protocol: TCP
    - port: 7670
      protocol: TCP
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: app-hysteria-hopping
  namespace: xui
  labels:
    app.kubernetes.io/name: xui
    app.kubernetes.io/component: app
spec:
  selector:
    app.kubernetes.io/name: xui
    app.kubernetes.io/component: app
  ports:
    - port: 9443
      protocol: UDP
    - port: 9444
      protocol: UDP
    - port: 9445
      protocol: UDP
    - port: 9446
      protocol: UDP
    - port: 9447
      protocol: UDP
    - port: 9448
      protocol: UDP
    - port: 9449
      protocol: UDP
    - port: 9450
      protocol: UDP
    - port: 9451
      protocol: UDP
    - port: 9452
      protocol: UDP
    - port: 9453
      protocol: UDP
  loadBalancerIP: 192.168.200.16
  type: LoadBalancer
