apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: xui
  labels:
    app.kubernetes.io/name: xui
    app.kubernetes.io/component: app
spec:
  selector:
    app.kubernetes.io/name: xui
    app.kubernetes.io/component: app
  ports:
    - name: web
      protocol: TCP
      port: 7700
    - name: web-sub
      protocol: TCP
      port: 7560
    - name: vless-1
      protocol: TCP
      port: 7554
    - name: vless-2
      protocol: TCP
      port: 7555
    - name: vless-3
      protocol: TCP
      port: 7556
    - name: vless-cf
      protocol: TCP
      port: 7670
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: app-udp
  namespace: xui
  labels:
    app.kubernetes.io/name: xui
    app.kubernetes.io/component: app
spec:
  selector:
    app.kubernetes.io/name: xui
    app.kubernetes.io/component: app
  ports:
    - name: hys-1
      protocol: UDP
      port: 7557
    - name: apl
      protocol: TCP
      port: 7558
    - name: hys-2
      protocol: UDP
      port: 7559
  loadBalancerIP: 192.168.200.15
  type: LoadBalancer
