apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - helm-repo.yaml
  - helm-release.yaml
  - hyvel-dns01-issuer.yaml
  - hyvel-dns01-token.yaml
  - wildcard-ho-hyvel-certificate.yaml
  - wildcard-hyvel-certificate.yaml
  - rbac.yaml
