apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: csi-proxmox
    namespace: csi-proxmox
spec:
    interval: 10m
    releaseName: proxmox-csi-plugin
    chartRef:
        kind: OCIRepository
        name: csi-proxmox
        namespace: flux-system
    values:
        config:
            clusters:
                - url: https://pve.ho.hyvel.eu:8006/api2/json
                  insecure: false
                  token_id: ENC[AES256_GCM,data:9+jMUzsDdUmwWpuqsLzH5NHu2b1d1w==,iv:jTnCtHvASEXGpu/YO4PGY6nA0STxRrDkLhmvC7ca6Ws=,tag:p1lKGhf0OlN9fgv8YgR6TQ==,type:str]
                  token_secret: ENC[AES256_GCM,data:jPuWyVyI1dGgMcGJpHIK9Kr9VmJiYTvchTOS9jxRDB51XQ0H,iv:2WlpjxG8YZ1JlS/GOzUbF836wQEy4q+j6luTSDfDNrE=,tag:LooPpbJR3Wm8bSWZ03t5pA==,type:str]
                  region: hone
        storageClass:
            - name: proxmox-data-sc-0
              annotations:
                storageclass.kubernetes.io/is-default-class: "false"
              storage: local-lvm-0
              reclaimPolicy: Retain
              volumeBindingMode: WaitForFirstConsumer
              allowVolumeExpansion: true
              fstype: ext4
              cache: writethrough
              ssd: true
              mountOptions:
                - discard
                - noatime
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUytwbk1ldENvNnQ1bUJl
            YjloaVdPRXM5bXZUME9vcnlsZHFFWkhLcWpJCkhoTjFCcUcxWE5kektPN0M2eENx
            Nmx0dkZQK2QwWW95MllvQlBvM2J5cTQKLS0tIFQ0ZytnRGc3Q29EUFhOT0VMM1dC
            RzNBVDNVUlAvWlFZS0pmOURmUTB1d2MKlbCjZ3MGfNzkPreJHlZrYabJwXKrXSOj
            5QAXct7f/K+1ACev7VNSr34aswOh9VnXj9+Qbq8pw9qyi69OKIHAUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1na9sc4yaxzdvt5jqpq99q3umg2qkhsv3use7lgej6lw46wz8sgrspg7a2h
    encrypted_regex: ^(data|stringData|email|token_id|token_secret)$
    lastmodified: "2026-05-26T09:36:12Z"
    mac: ENC[AES256_GCM,data:ZENoPGTeWaJ5RdMRfB+vhbcvgm+5RKpFyrCvI/frq9hQAmOIJr+0uyp9B8QlM+++3LTSvaN3A4byj37C9Ep/A3VqyxjspOkALyUbb67J3AuidXWVADKR060oG5UrMepXE2bPUh84xzc5rJxIzC8kNOpF1/MplGNPhBYa07uuOlM=,iv:6rCTbZs5qx4I9C7svMYq4lBvJzHCMf80ZHzYzuXXWV0=,tag:Y9v3C2AvDqxUoJLZwi7/BQ==,type:str]
    version: 3.13.1
