apiVersion: v1
kind: Secret
metadata:
    name: app
    namespace: vw
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:rbKz21fKTarCQDerfCkXsOt45aVYS9Rqbv78ofXUxk44Gp+OrQTBj6v+WSs=,iv:NwHvZa7p5NARp/9wNegJn/zIkNqFgNg6F1hY62HHYjk=,tag:vMmcwITnkZfafJa4nsDSCA==,type:str]
    ADMIN_TOKEN: ENC[AES256_GCM,data:w61oCa5FYNLg2m+5/G5BMscylhYbHy5kGcJvDjiuD/fj3zmfIvVSxJnhVpOHEZGh1F9gzHetvN0x9vttgILtLOIHBp3DnS8utG+tRrHRZdwzcQAJSGeI4mm7aymMA5iVyLL4oU5J46nwak33nbZbrJCn03WGdfkB2zFaQp/CXdlsKuYuhzc=,iv:FrtMyMadftFpUVQaqNMrEmLDaue3nq1HOWcWHS0+CGw=,tag:FrNqGe7xU4J8N59+00hrgg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVaGFzSi9pVUdvSlV3MXRJ
            OHNPcGMvUnRBWTJqUVhHMktvakxzdU9oRGxJCmZHeS94UXZuK1pwQ3BkS2gzVmpO
            Y2VkeWhQVXplSDFaaVd0V2IxRy9lNmMKLS0tIC81a1NxL2pwbUhSMGN0Tzh0eERi
            QkRwMmp3bmYzTHJ0dFE2NXBEaHAwN28K488gNp2kQm51qhBgzx2I/pbst5GwYGHx
            dMjYReZEib2L7YI3kD8XPyp9r3f0u0A+shy0MJ5NYK1MiwzmMJ6wGQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1na9sc4yaxzdvt5jqpq99q3umg2qkhsv3use7lgej6lw46wz8sgrspg7a2h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T06:59:25Z"
    mac: ENC[AES256_GCM,data:a5RLTbOI+vV1BnxmOkahKvhelWHbmwvJ3POST4gqyD8VQp5t18aN8GmAdCKH7fcLPFpPfipC76V+YsikokgQCtjb0GqOTYb324GjMR11osE6LmQhxAgwCQlQQR3zsFe84wVH4xL8TanZuepeUE+2lOBERTgDiEIYoo5ROLjNI1g=,iv:agjlc9bpOdSYTF/b9UyLyOvjoUHDtoz4JP0tcmSQCn0=,tag:pwErKlxPApBadpDaalGwdw==,type:str]
    version: 3.13.1
