apiVersion: v1
kind: Secret
metadata:
    name: db
    namespace: vw
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:6ea9vGGD11Ynaqs3ujhkfqQMKwE=,iv:ZDiylI8uIqEOi2AUJ4U30clvKNqHW0FUl+JobMj1AM4=,tag:EleKvEOcaKUnjH4cskn4Sw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVzd5Z3NmQU4wRGtQb1VT
            dE1aVVk2R05RNS9ReERFT0xnSWRmNVFQSWg0Ci83STFvdXd3Y2dYbG96dzFJdkhN
            NGlZTU01QmVPNlRmRkpOZE5iRjhYWnMKLS0tIENoMlFtbWJCazBJNDBqeXZSOXFS
            a2VPT0NHMW50L25Jc3RLUUxXaG9FcVUKjdJ5JSZuzsOdmYr0Mq6sF+Qql8yGacIw
            U3YAppwyb85aJr2DfjHmFKOG2eBvofZ1O1g4pgHaYXKa5pl8Nv60Hg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1na9sc4yaxzdvt5jqpq99q3umg2qkhsv3use7lgej6lw46wz8sgrspg7a2h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T06:59:31Z"
    mac: ENC[AES256_GCM,data:9eqgKMquEsPpCMIWQujEIpaRfxlx5UfpZP/iDLWfH1ONLYvUhY+bnoNrzQzo/sSI2WtDQwcJC39egj0bjbbeaxWyavmF+ejF9wxRdmUm/jSk96blTd3xFblhxXSQ/Yw4wFTb20XKcCgLt+3DgVMttgU1g90atXdMWCHV1HFFII4=,iv:11RfRJIF1tZM0vDACEsCB5dxmOBteHVOgjK0MP7STZc=,tag:wjt/9H9cTAz8aWMi1Nt1Ow==,type:str]
    version: 3.13.1
