apiVersion: v1
kind: Secret
metadata:
    name: k8up-yint-minio
    namespace: k8up
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: lldap,qbt,ts,authelia,immich,vw,xui
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
type: Opaque
stringData:
    minio-username: ENC[AES256_GCM,data:rHMelQ==,iv:k6ziVUE3SmOIT4V4ZWvTpVLPx8Wsp8GQYwyE2XUJFBQ=,tag:oTx3QMU3qNpRFJI6CGdRmw==,type:str]
    minio-password: ENC[AES256_GCM,data:nCuot34oC9jB5ZyP0UV4/z99mFg=,iv:njrpP+XQudiZefqkzSKtMe4YH13DX0ASZwvUfdg9G/Q=,tag:yD4xUfST1F2q01kSWTRwIA==,type:str]
    repo-password: ENC[AES256_GCM,data:oPKZ5FmIjSannQD2nmPv/lKsRBU=,iv:IeEdX5pbK12uCWRVCcQEOrJF8UMyfaOPYSqTbHqJNm4=,tag:YOeE0SafnX44FfZ8oKZvEw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbnpWaWpFdURHdEhoZkRL
            Tm51VUJyVnM0VzBMVUZhTHovVENlNnN0MW1jCjFrb1kxZmVoMUNLTThVZ3pIUS85
            U09kd0NVdkVGczl2QlJJQm40NVRDSDgKLS0tIHE3Tlhjb1V0NVhJUXgzck1MUmJp
            bURxL1dVRkZPY2R0NVdnM0REZUpYMmMKQArw99rSfAX/L2XHSKWlpPNepuvFEvmU
            BmEGplIYXoHTtWxY1K8p8fX8EOmDXBBZWSeYnlN1RT1aIzfu8nbILg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1na9sc4yaxzdvt5jqpq99q3umg2qkhsv3use7lgej6lw46wz8sgrspg7a2h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T07:42:55Z"
    mac: ENC[AES256_GCM,data:olExRWvRXVmDUvECsAX/F2uDM93eVRLMNm7EVyG8/K7aL2v2+lDvZ25IzVDUPhUqgdf3uS73PWWTHEuZisWGkmbyzIO+3Cw3KbXX8p0T549hNTbK6ZnxHiKJECml1YEcl19wLeo2G2uozGYuQnzNabqh+tGUvwqHxqeiGmHOjmw=,iv:jEDc73V0cUVw3dWt9coiCIhctWXUisjAGash7MsOC58=,tag:sjg85m41OtN0qAPXoSCVAw==,type:str]
    version: 3.13.1
