apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db
  namespace: authelia
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-data-sc-0
  resources:
    requests:
      storage: 3Gi
