apiVersion: v1
kind: Secret
metadata:
    name: k8up-yint-minio
    namespace: k8up
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: lldap,qbt,ts,authelia,immich,vw,xui
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
stringData:
    minio-username: ENC[AES256_GCM,data:rHMelQ==,iv:k6ziVUE3SmOIT4V4ZWvTpVLPx8Wsp8GQYwyE2XUJFBQ=,tag:oTx3QMU3qNpRFJI6CGdRmw==,type:str]
    minio-password: ENC[AES256_GCM,data:nCuot34oC9jB5ZyP0UV4/z99mFg=,iv:njrpP+XQudiZefqkzSKtMe4YH13DX0ASZwvUfdg9G/Q=,tag:yD4xUfST1F2q01kSWTRwIA==,type:str]
    repo-password: ENC[AES256_GCM,data:oPKZ5FmIjSannQD2nmPv/lKsRBU=,iv:IeEdX5pbK12uCWRVCcQEOrJF8UMyfaOPYSqTbHqJNm4=,tag:YOeE0SafnX44FfZ8oKZvEw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbnpWaWpFdURHdEhoZkRL
            Tm51VUJyVnM0VzBMVUZhTHovVENlNnN0MW1jCjFrb1kxZmVoMUNLTThVZ3pIUS85
            U09kd0NVdkVGczl2QlJJQm40NVRDSDgKLS0tIHE3Tlhjb1V0NVhJUXgzck1MUmJp
            bURxL1dVRkZPY2R0NVdnM0REZUpYMmMKQArw99rSfAX/L2XHSKWlpPNepuvFEvmU
            BmEGplIYXoHTtWxY1K8p8fX8EOmDXBBZWSeYnlN1RT1aIzfu8nbILg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1na9sc4yaxzdvt5jqpq99q3umg2qkhsv3use7lgej6lw46wz8sgrspg7a2h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-26T05:05:34Z"
    mac: ENC[AES256_GCM,data:6xWh0S+rvoNEBGZ8cl+OPl/o2jNVFrFvTJQg9aplClaaEv0HqUf94vuiIubgbsuH9eHcU4OdUSFHz4+65A0pJ6RAgyPx8xMzAXAbFCdO9wGousQT4BTkc6WYWFV7drIMcnYM6+nuZEgCI2U4YKbw6loU2lQYaCUzYHr+SHoEjfg=,iv:XN3IzaYkolr1Y4bIB1Ax4azuhdwYu/PIcnG/h3DJtFs=,tag:D9p5Z7JSTZ2FepFXMCTcbA==,type:str]
    version: 3.13.1
