apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: csi-proxmox
    namespace: csi-proxmox
spec:
    interval: 10m
    releaseName: proxmox-csi-plugin
    chartRef:
        kind: OCIRepository
        name: csi-proxmox
        namespace: flux-system
    values:
        config:
            clusters:
                - url: https://pve.ho.hyvel.eu:8006/api2/json
                  insecure: false
                  token_id: ENC[AES256_GCM,data:E6FdR7rjPXZmRq0WKsO64ZmM65E5Ig==,iv:QQPL3hdvfk7SsR64tFyoq8PBuhz4QFNwT6ny0q6vYOE=,tag:kHjjl++OskreYb7eI5+57Q==,type:str]
                  token_secret: ENC[AES256_GCM,data:qIYnLOSe3cfmTV7ebztTzbCH2hEgRDQft7fcgx+9Nw2DDNM+,iv:vCYtLFse2+MAh2ySYrNDtORnS7innq/JAAcQmg6R3ms=,tag:JAJ0w0pv/fzcDmBaDDMeoQ==,type:str]
                  region: hone
        storageClass:
            - name: proxmox-data-sc-0
              annotations:
                storageclass.kubernetes.io/is-default-class: "false"
              storage: local-lvm-0
              reclaimPolicy: Retain
              volumeBindingMode: WaitForFirstConsumer
              allowVolumeExpansion: true
              fstype: ext4
              cache: writethrough
              ssd: true
              mountOptions:
                - discard
                - noatime
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDcGw4T1FTVHhGMThvTDNo
            RTJBQ3JRd1FEK1NuUkNnOFlDNEdqaFRvZW13ClNaVTVWUkpPWE1TRGRpdnljRDVT
            dXZPUE5RNzlWWEhYRXpYOHFNNVZrdk0KLS0tIFdKK3ZUa0p5RSsrTTBxdll3UGNa
            cjRyMzcwWmRSQVlOVUxvcVFVcjBFZzAKwdsrlHtmLCUD/F6pA52Gri2LQ/GCphGw
            VFG/jOrPK1dkaoCDrHmCd/7pf31O0FG+sHpNSgvSDp8bQ/h4ZGPiRg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1na9sc4yaxzdvt5jqpq99q3umg2qkhsv3use7lgej6lw46wz8sgrspg7a2h
    encrypted_regex: ^(data|stringData|email|token_id|token_secret)$
    lastmodified: "2026-05-26T09:20:12Z"
    mac: ENC[AES256_GCM,data:HRycBiPV5DE1CxCLvfP5m4wqA1AuYWeale/vPLF7pV4n8L9CVaky7oR4LlKb65oSbOwac4gF+K7I/yDa793Mwzj8Lf4nWfTBScs/lF68by7suFA8r/+nD/WXbvAe6KGWpzHH3PWGjURrYRWLw9yNbbxYQAeAI8R+SoPs2E5/mvM=,iv:vd3LJJfxIxoZPU4m35IaCVn2pYYc68hlk/eE6Vlukrw=,tag:xs2bYGHazIoJXMzVUbjPsQ==,type:str]
    version: 3.13.1
