apiVersion: v1
kind: ConfigMap
metadata:
  name: config-app
  namespace: turn
data:
  turnserver.conf: |
    listening-ip=0.0.0.0
    min-port=50201
    max-port=65535
    use-auth-secret
    static-auth-secret=FILLME
    realm=trn.hyvel.eu
    cert=/etc/turn/certs/tls.crt
    pkey=/etc/turn/certs/tls.key
    fingerprint
    verbose
    no-cli
    no-tlsv1
    no-tlsv1_1
    no-tcp
    no-udp
    no-rfc5780
    no-stun
    no-multicast-peers
    no-software-attribute
    no-stun-backward-compatibility
    response-origin-only-with-rfc5780
    denied-peer-ip=10.0.0.0-10.255.255.255
    denied-peer-ip=172.16.0.0-172.31.255.255
    denied-peer-ip=192.168.0.0-192.168.255.255
    denied-peer-ip=127.0.0.0-127.255.255.255
    denied-peer-ip=::1
    denied-peer-ip=fc00::-fdff:ffff:ffff:ffff:ffff:ffff:ffff:ffff
