apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kgateway-crds
  namespace: kgateway
spec:
  interval: 10m
  releaseName: kgateway-crds
  chartRef:
    kind: OCIRepository
    name: kgateway-crds
    namespace: flux-system

---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kgateway
  namespace: kgateway
spec:
  dependsOn:
    - name: kgateway-crds
      namespace: kgateway
  interval: 10m
  releaseName: kgateway
  chartRef:
    kind: OCIRepository
    name: kgateway
    namespace: flux-system
