apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: hyvel-dns01-issuer
spec:
    acme:
        email: ENC[AES256_GCM,data:/kyA1JePKqEtFJ2QnB1tjHQvJiYtbV7vIkihqg==,iv:cCcbv22teLVBjafR8jgSF/DivTdGu0DBhkWREI7pC+s=,tag:ytdQ5MiyQiRmiYvhlMZcJQ==,type:str]
        server: https://acme-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
            name: hyvel-dns01-issuer-account-key
        solvers:
            - dns01:
                webhook:
                    config:
                        apiKeySecretRef:
                            name: hyvel-dns01-token
                            key: token
                    solverName: desec
                    groupName: acme.pr0ton11.github.com
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTTGpCYWthTWw1Vm1nTFdx
            dEhsQmR2Z1VjZlU5eVIvVXg5M09jdDlNa0FZCjVCeFJJRkJQZzdaclFIWkxGb2FH
            d2dNMmQvcEpab25GNlhFWXdXaGg4YWMKLS0tIEVWTW1zVzh3Wlc2N29VWUJZWU1j
            ZlBIWlhGblhtU2ZqUTU0TVBKMUY5TzgK/rHWejoiiVyjaL8ASq5FxrJfdAylcZ12
            yza5++rtQrT4itbwhjqf1Jno1vbBvdfuKq/zl4R5dHS9I17u/VvoJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1na9sc4yaxzdvt5jqpq99q3umg2qkhsv3use7lgej6lw46wz8sgrspg7a2h
    encrypted_regex: ^(data|stringData|email)$
    lastmodified: "2026-07-29T06:09:09Z"
    mac: ENC[AES256_GCM,data:axP1b+Dwb8pnEgavOgXoe9jBn9ivFzAoYo+CU3I2f+wIQ6PAsbFHxtfwMv0c7g7kJb8oURy7CyiFr1Nv6GPYzKT69tt9EGo66IZppDIss/iMkMosrc2FcOhgWESsebw3aJxoPl9izU1FCOxEr7itDVaQoOnI22+8oks+U3SfJnc=,iv:3Elsp/TKGRltpR+rY0M37NfnYKcyl/kWDLii2fzm01E=,tag:RStWdd2H/70cyA0j3CstGw==,type:str]
    version: 3.13.1
