apiVersion: v1
kind: Secret
metadata:
    name: hyvel-dns01-token
    namespace: cert-manager
stringData:
    token: ENC[AES256_GCM,data:Zezza+tqnxtohi49lO6QZ3PucFNhKynG/OjV6g==,iv:hvR4jdyETMJw3z83DFvDkWubyEZFbMyEwPi1xfsSlDU=,tag:jezJWpaIuJv7hYUd916Exg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqLzRheFF0WEVkUVhrN2VO
            Umo0VEtUY0VMdjJxUDUyclc3NlRSV2xESzBvClk0NzY5UWVCWVNZN3RlNnpRMW9s
            NjZDVVFKZ3VNR0pYanA1NDRIVGprLzgKLS0tIERVbFJZZmFhcDJ6UUdoNEF5eG16
            NWUxNmNzOGdSQ0xuRitMcUIzaHZaUjQKZmgR5LItkG1CQckp/sgDB5dw3IWP9hsQ
            GbX/O5vBFxx1ML88V8VjQLViFmOMregHydSAXLGgyPTlyNQV79dHxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1na9sc4yaxzdvt5jqpq99q3umg2qkhsv3use7lgej6lw46wz8sgrspg7a2h
    encrypted_regex: ^(data|stringData|email)$
    lastmodified: "2026-07-29T06:02:57Z"
    mac: ENC[AES256_GCM,data:56cbuEiwArYDEliOOv1IlcuZxz6NFnCjaHqBq/ue4bn8NRL4fgGvELhFPHkzd1QULRFeFNoaDMMHMeUtl6/BPRaYy97aECbyQOxtTWaPkPv+w3sIW3P6HCuRbpvtyofwbQoaeIBSlm2F+IGbJrdgq4VTcAM0y6iWUx7Mdmd3BfE=,iv:YoULXtMrhUoHMoMyhrktRFEaDYM2Yo+XxWa8Kloubgw=,tag:+Zs5Zy9BDMIVHvb5G8wfFA==,type:str]
    version: 3.13.1
