apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: hyvel-dns01-issuer
spec:
    acme:
        email: ENC[AES256_GCM,data:/kyA1JePKqEtFJ2QnB1tjHQvJiYtbV7vIkihqg==,iv:cCcbv22teLVBjafR8jgSF/DivTdGu0DBhkWREI7pC+s=,tag:ytdQ5MiyQiRmiYvhlMZcJQ==,type:str]
        server: https://acme-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
            name: hyvel-dns01-issuer-account-key
        solvers:
            - dns01:
                cloudflare:
                    apiTokenSecretRef:
                        name: hyvel-dns01-token
                        key: api-token
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTTGpCYWthTWw1Vm1nTFdx
            dEhsQmR2Z1VjZlU5eVIvVXg5M09jdDlNa0FZCjVCeFJJRkJQZzdaclFIWkxGb2FH
            d2dNMmQvcEpab25GNlhFWXdXaGg4YWMKLS0tIEVWTW1zVzh3Wlc2N29VWUJZWU1j
            ZlBIWlhGblhtU2ZqUTU0TVBKMUY5TzgK/rHWejoiiVyjaL8ASq5FxrJfdAylcZ12
            yza5++rtQrT4itbwhjqf1Jno1vbBvdfuKq/zl4R5dHS9I17u/VvoJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1na9sc4yaxzdvt5jqpq99q3umg2qkhsv3use7lgej6lw46wz8sgrspg7a2h
    encrypted_regex: ^(data|stringData|email)$
    lastmodified: "2026-07-10T09:49:36Z"
    mac: ENC[AES256_GCM,data:kAvr1NYxsR2lesjN1neRrW1GUbz2rpGaCOAUyDJkwhEw/RYXBOMQU0uZcPALUdFvz/w2JJ6XUHomn+t0cvGtRcdJ8TiObgmdlFcBP2C43MDa0FglOkq3vLI05wnXBxwIz3Jknvn0OrZSgtm41q2eNDeOibC3JGGtQV5eJajyMM8=,iv:avCOkMO3Izwq0YTZWnFGoPuKwYnc9bOzRRenLywyYiw=,tag:5i2MxlLyHSAXDpVKE/KloA==,type:str]
    version: 3.13.1
