apiVersion: v1
kind: Secret
metadata:
    name: hyvel-dns01-token
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:4RQhajtfsZhxQ54Xlcay3opXcbadpuIC++8L+lYArVuAXVyFDXBRfO/TbdEe40ZNYEeOZqA=,iv:TpRAk8U7Hz951UHzGJ2WKVcONZVbvMhJqnlK3cl6/tE=,tag:HLDBdDa+pfeJCOoeVO3chQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqLzRheFF0WEVkUVhrN2VO
            Umo0VEtUY0VMdjJxUDUyclc3NlRSV2xESzBvClk0NzY5UWVCWVNZN3RlNnpRMW9s
            NjZDVVFKZ3VNR0pYanA1NDRIVGprLzgKLS0tIERVbFJZZmFhcDJ6UUdoNEF5eG16
            NWUxNmNzOGdSQ0xuRitMcUIzaHZaUjQKZmgR5LItkG1CQckp/sgDB5dw3IWP9hsQ
            GbX/O5vBFxx1ML88V8VjQLViFmOMregHydSAXLGgyPTlyNQV79dHxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1na9sc4yaxzdvt5jqpq99q3umg2qkhsv3use7lgej6lw46wz8sgrspg7a2h
    encrypted_regex: ^(data|stringData|email)$
    lastmodified: "2026-07-10T09:47:10Z"
    mac: ENC[AES256_GCM,data:RwwpY9OgzkXJFyuZv5p2wo5UvBB7PBX19LihZTH/mVFfED0wrqkvLj+zRRZ699dSJ0OjSKOclBDpslr7X/aj2Dgp5x3SA7AHD9NqSROAInSgBq/9can3zzDyb0kWcouf1SHMOQOEtURLwWT7uw8P0N901hLf4S230w9/uGy/4KQ=,iv:VUUmQk3Zh0plcjQcpjxqmx2H1qjE2tCz1vvzpSKrws8=,tag:kgLfqTZGJJm7jwuGb5r8iw==,type:str]
    version: 3.13.1
