apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: hyvel-dns01-issuer
spec:
    acme:
        email: ENC[AES256_GCM,data:/kyA1JePKqEtFJ2QnB1tjHQvJiYtbV7vIkihqg==,iv:cCcbv22teLVBjafR8jgSF/DivTdGu0DBhkWREI7pC+s=,tag:ytdQ5MiyQiRmiYvhlMZcJQ==,type:str]
        server: https://acme-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
            name: hyvel-dns01-issuer-account-key
        solvers:
            - dns01:
                webhook:
                    config:
                        apiKeySecretRef:
                            name: hyvel-dns01-token
                            key: token
                    solverName: desec
                    groupName: acme.pr0ton11.github.com
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTTGpCYWthTWw1Vm1nTFdx
            dEhsQmR2Z1VjZlU5eVIvVXg5M09jdDlNa0FZCjVCeFJJRkJQZzdaclFIWkxGb2FH
            d2dNMmQvcEpab25GNlhFWXdXaGg4YWMKLS0tIEVWTW1zVzh3Wlc2N29VWUJZWU1j
            ZlBIWlhGblhtU2ZqUTU0TVBKMUY5TzgK/rHWejoiiVyjaL8ASq5FxrJfdAylcZ12
            yza5++rtQrT4itbwhjqf1Jno1vbBvdfuKq/zl4R5dHS9I17u/VvoJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1na9sc4yaxzdvt5jqpq99q3umg2qkhsv3use7lgej6lw46wz8sgrspg7a2h
    encrypted_regex: ^(data|stringData|email)$
    lastmodified: "2026-07-29T06:14:27Z"
    mac: ENC[AES256_GCM,data:x+ToW1SBcVCka2T+zCU3PIbe9j/eLU2nIg5wmQOq1h+Uc+SlHlYUxfZcDFVCpCRRHhvRYR+vy04SLCYGmCZe3FzpcNklmy67Er8PSqF9YKqwMrlIFOEYZyfmtLB3vbR+EPfb4IWUKOXjDXk0m9B/gCfUktWk5i8APeyby7s5sYg=,iv:x1Q8uhrwqrAac1zsEB1cZHJ4h3ZXkHSuULx+2fjsI/s=,tag:FRTORDT5dToY+BNJUNMqIQ==,type:str]
    version: 3.13.1
