apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-app-pvc
  namespace: vw
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-data-sc-0
  resources:
    requests:
      storage: 3Gi
