apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayExtension
metadata:
  name: anubis
  namespace: kgateway
spec:
  type: ExtAuth
  extAuth:
    httpService:
      backendRef:
        name: app
        namespace: anubis
        port: 7580

      pathPrefix: /.within.website/x/cmd/anubis/api/check/

    headersToForward:
      - authorization
      - cookie
      - x-forwarded-proto
      - x-forwarded-for
      - x-forwarded-method
      - x-forwarded-host
      - x-forwarded-uri