apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayExtension
metadata:
  name: authelia
  namespace: kgateway
spec:
  type: ExtAuth
  extAuth:
    httpService:
      backendRef:
        name: app
        namespace: authelia
        port: 7702

      pathPrefix: /api/authz/ext-authz/

      authorizationResponse:
        headersToBackend:
          - Remote-User
          - Remote-Groups
          - Remote-Name
          - Remote-Email

    headersToForward:
      - accept
      - cookie
      - authorization
      - proxy-authorization
      - x-forwarded-proto
