apiVersion: v1
kind: Secret
metadata:
    name: smb
    namespace: qbt
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:a9aReWurHQ==,iv:pmshdlVWFy+hmNpxr9EqE9eeYe4KLKeJ/FC4yK8Jgwk=,tag:979JJlgmhQmHMBlGDbVftw==,type:str]
    password: ENC[AES256_GCM,data:lXxDXG3OpA6oMf0ohqHnhA==,iv:tp/+IxZFMHpByIuuoZfNY8V2e+OcqJwNxakx+qzSk8E=,tag:31Jtv14BXCdJRNaek4SV+g==,type:str]
    domain: ENC[AES256_GCM,data:ePkgKSSoQeUuFW3ZlugAaJQ=,iv:lzzZCettokzfmz2nB/k4Y6PFHFdJCsqrmywIakAgg60=,tag:1zS92wuyvrIC2OBSfaqFkA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MFpwdHB1RHBPSDFueTdD
            b3JDUkFSRndERmhpVTl1L0tSZlREYWtQb3ljCi93VHJvV0RITHRRTUYzZ3RMNEpJ
            d0tuaTlwRlcxR2xid1VRWGNURHBOOWsKLS0tIE9UTDlYay9ZWkNxZFM5OWF3dkFI
            eGhCaXpaZENMMWZYK0kyVW5DME5hYmsKajy2o2BLm7nqQ0Pz87q4CYpAzb76mcZA
            iu2CD+DS4nnjziUVAw29DJPvpci4sMqMbotxB8gEjZOim0RgrYeRFg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1na9sc4yaxzdvt5jqpq99q3umg2qkhsv3use7lgej6lw46wz8sgrspg7a2h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-23T06:01:50Z"
    mac: ENC[AES256_GCM,data:HmcHvSIRUXUIED+/aXcFQ9vK+rro4LdBjQjXMbIJTW1sL0bn/3Pgk2eE6mxJSHBO5nNJBiQxbOfsAejOfTaL39DPjQ9Y0HPeN/m+MDc3Lw/Ft+xjsLX9xGVnJOJ5c+p7Zlem5hIWA8C20wSpfSsGY5y4SgGQRxAVhM6Dt9BVCV4=,iv:LkzLe7gK3RiTkDIHEWqD+XL1zWvdSTdg1T6SxvCcnx8=,tag:+vxLj0zJKkZevP+xuFrC7g==,type:str]
    version: 3.13.1
