apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: authelia
  labels:
    app.kubernetes.io/name: authelia
    app.kubernetes.io/component: app
  annotations:
    secret.reloader.stakater.com/reload: "app-config"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: authelia
      app.kubernetes.io/component: app
  template:
    metadata:
      name: app
      labels:
        app.kubernetes.io/name: authelia
        app.kubernetes.io/component: app
    spec:
      volumes:
        - name: app-config
          secret:
            secretName: app-config
      containers:
        - name: authelia
          image: authelia/authelia:4.39.28
          envFrom:
            - secretRef:
                name: app
          volumeMounts:
            - name: app-config
              mountPath: "/config/configuration.yml"
              subPath: configuration.yml
              readOnly: false
              
          startupProbe:
            httpGet:
              path: /api/health
              port: 7702
              scheme: HTTP
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 12
            
          livenessProbe:
            httpGet:
              path: /api/health
              port: 7702
              scheme: HTTP
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            
          readinessProbe:
            httpGet:
              path: /api/health
              port: 7702
              scheme: HTTP
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
