apiVersion: v1
kind: Secret
metadata:
    name: db
    namespace: authelia
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:ob+oZnmyEfQ3pNDNxf32gxUs9j9k9faNdLCV/hxh,iv:ETZGTag1PSci/Sk2nWioR0ic42J3HQa/LjvXKAq+q+I=,tag:ehE+d+FwEVtUIjF++pGWNw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpczBWdWk4NjduNDZPRHRO
            M2J4eWhPbFRnb1lNT2ZQTHhEQjVPL2pLUzM0Cml2blJrbzZqWVdCa3l5OXJ6cDdY
            ck54ajdlR0NERzUxN29nWUwxOThYZFkKLS0tIEgrc2JuYTRsVmNzb2cvYXEzaENi
            U1ZBMDB2VFJINEpBelh5SHhieWhwbkEKvix0LX09kgDNhheFG6mMvdS/u8zRNQgk
            EGsLICnbmTocLIRz3OuLhU7WiV2rB9IvqwJJUiGnKlvOMcv8x5xoXg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1na9sc4yaxzdvt5jqpq99q3umg2qkhsv3use7lgej6lw46wz8sgrspg7a2h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T06:51:00Z"
    mac: ENC[AES256_GCM,data:86v6UOFCzd99ocjqmJKDk9LRJFbeUV4HBldCp7qNR5uqinG0rXLBX8E/Rz8PTS7HwbmkvEb0rPtx5/T7XhV0Bf+tkD4ko0KwBLHj9R0QJ2fU5XPObwM4zumsaYuZi7bK3P5ICOXajPIkCPTOYlKBtEUDqFrr39fArSQILLevAos=,iv:rg89N1jUbq0nZJS5aepkNzt8oUApF0EIVmbNOuFHBdo=,tag:ul5dpKGpLiFMj7+DnWRYxA==,type:str]
    version: 3.13.1
