apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-db-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-data-sc-0
  resources:
    requests:
      storage: 3Gi