apiVersion: v1
kind: Secret
metadata:
    name: db
    namespace: immich
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:L80Brk+EiC8QCV7M6pgdfnIzM7o=,iv:/IzVelhtDUOxHlOvl72BiJ+qS+Hd045bbhB6+n9OnBQ=,tag:xXxzRW52MIVLgo/gZgDwJg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dGVzTC9JemwwWFRHdVBS
            SUZWZnFrcnI3Sm1IdnpnUzg4SEYyQVY5Y0JrCjJlWmFtS3BwZG9qOW5WVmJlUnA2
            ZU5FSTBFN0VkYngzS1k1SHl4bU83am8KLS0tIGNaUnRlVGNadGh6TDNSUElPb1ht
            UlU3VTh3a2MrT3NOR2dnQ2VYT2plcnMKmsbX5YIBpUViSwAERcaXW6lTdLzazEKZ
            o8CR/Ja+DU9KldHZ3GQQx8SmISKLX6HPUC152N0l8mEBy4dQqtFhkQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1na9sc4yaxzdvt5jqpq99q3umg2qkhsv3use7lgej6lw46wz8sgrspg7a2h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T07:13:07Z"
    mac: ENC[AES256_GCM,data:mz+yYFvaiL/Y1PfGdnc/b3sFo71XeqQ4t5lxP3+ZCvk6QrwXhRbjObUCzckkV/15iaFcbhkXuqwmF548pC9XLzceojYG8tvXC6OmDq8p7vdECanCnZdeGg7OFwabgPpWfQyxvZMLN9kW+62ugpZYto86Su2Afuuh/ai5Jjcoddk=,iv:wGfK86fKpPRRhV15pMNuBYrfl53SofavoYqzeWtUPYI=,tag:GdWFrxAP8aGxmPy+JS1JqA==,type:str]
    version: 3.13.1
