apiVersion: v1
kind: Secret
metadata:
    name: app
    namespace: immich
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:mK4T+RshPV/8mSYjTKqfpSxBLoA=,iv:K3fUEXrid2LnGkuRrT//LTZ2VEk1fNrR21QaB92xQ0Y=,tag:vgmtXzUXpZ/3c16Ta+rpBQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQcjRzNTZ2RVRpMkxuV0Zu
            VWxjU2pYUzhzajRZVURxQUltakRPU0RTK0h3Cm55MnpUNTdVN2xjand6SVhRZVFI
            STZPbVdRZEljeGJ5a0JlUUlTTDVmck0KLS0tIE1FQmdYSkYzRURBSDRDbGNhdzEy
            NkFiaDM2MGRSclpoelIydkFPU20xKzAKsP//pIStUMyujbLXhTNUu4KqA0VgVFDB
            YVS98GBDGsxi9hkMTjHPZttn1rpGUVsGFpXgUGTXnNQ/eu9opa2vaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1na9sc4yaxzdvt5jqpq99q3umg2qkhsv3use7lgej6lw46wz8sgrspg7a2h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T07:13:04Z"
    mac: ENC[AES256_GCM,data:3jRpz+9L6FXbDnIHQYMUlGkkM0z8eTvGIPXMFtk65c5TiTCrtLXuBlzOqNHoB9ODwsAbglY/Qdjh3H530rPI8z8BbISr1rjXOIbBchco+3vmOJhYwnUuIqnDLWNZw4Cg20sOmZX2tx0AqznvETuZb41uTsgBf+SruZyYn9N/lJc=,iv:6p4tinxL8Ihb3qHxcngYPGhnIv23yilQLFvgwuymcaQ=,tag:j51ccb8y9lMrYMtJ3Yomwg==,type:str]
    version: 3.13.1
