apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: tproxy
  labels:
    app.kubernetes.io/name: tproxy
    app.kubernetes.io/component: app
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: tproxy
      app.kubernetes.io/component: app
  template:
    metadata:
      name: tproxy
      labels:
        app.kubernetes.io/name: tproxy
        app.kubernetes.io/component: app
    spec:
      volumes:
        - name: runtime
          emptyDir:
            medium: Memory
            sizeLimit: 4Mi
        - name: app
          secret:
            secretName: app
      containers:
        - name: tproxy
          image: ghcr.io/telemt/telemt:3.5.7
          workingDir: /run/telemt
          args:
            - /etc/telemt/config.toml
          volumeMounts:
            - name: runtime
              mountPath: /run/telemt
            - name: app
              mountPath: "/etc/telemt/config.toml"
              subPath: config.toml
              readOnly: true