apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: tproxy
  labels:
    app.kubernetes.io/name: tproxy
    app.kubernetes.io/component: app
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: tproxy
      app.kubernetes.io/component: app
  template:
    metadata:
      name: tproxy
      labels:
        app.kubernetes.io/name: tproxy
        app.kubernetes.io/component: app
    spec:
      volumes:
        - name: app
          secret:
            secretName: app
      containers:
        - name: core
          image: ghcr.io/sleep3r/mtproto.zig:1.15.2
          volumeMounts:
            - name: app
              mountPath: "/etc/mtproto-proxy/config.toml"
              subPath: config.toml
              readOnly: true
              