apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: tproxy
  labels:
    app.kubernetes.io/name: tproxy
    app.kubernetes.io/component: app
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: tproxy
      app.kubernetes.io/component: app
  template:
    metadata:
      name: tproxy
      labels:
        app.kubernetes.io/name: tproxy
        app.kubernetes.io/component: app
    spec:
      volumes:
        - name: app-1
          secret:
            secretName: app-1
        - name: app-2
          secret:
            secretName: app-2
        - name: app-3
          secret:
            secretName: app-3
      containers:
        - name: tproxy-1
          image: raylabpro/telemt:3.4.15-alpine3.24
          volumeMounts:
            - name: app-1
              mountPath: "/etc/telemt/config.toml"
              subPath: config.toml
              readOnly: true
        - name: tproxy-2
          image: raylabpro/telemt:3.4.15-alpine3.24
          volumeMounts:
            - name: app-2
              mountPath: "/etc/telemt/config.toml"
              subPath: config.toml
              readOnly: true
        - name: tproxy-3
          image: raylabpro/telemt:3.4.15-alpine3.24
          volumeMounts:
            - name: app-3
              mountPath: "/etc/telemt/config.toml"
              subPath: config.toml
              readOnly: true
