apiVersion: traefik.io/v1alpha1
kind: ServersTransportTCP
metadata:
  name: ingress-pp
  namespace: tproxy
spec:
  proxyProtocol:
    version: 2

---

apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ingress-proxy
  namespace: tproxy
spec:
  tls:
    passthrough: true
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`repository.su`)
      services:
        - name: app
          port: 7770
          serversTransport: ingress-pp

---

apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-headers
  namespace: tproxy
spec:
  headers:
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 63072000
    customResponseHeaders:
      server: ""
    permissionsPolicy: "camera=(), microphone=(), geolocation=()"


---

apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: http2tls12
  namespace: tproxy
spec:
  minVersion: VersionTLS12
  maxVersion: VersionTLS12
  alpnProtocols:
    - h2

---

apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: hide-h3-header
  namespace: tproxy
spec:
  headers:
    customResponseHeaders:
      alt-svc: ""

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-plain
  namespace: tproxy
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`cache.hyvel.eu`)
      middlewares:
        - name: traefik-https-redirect
          namespace: traefik
      kind: Rule
      services:
        - name: noop@internal
          kind: TraefikService

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress
  namespace: tproxy
spec:
  tls:
    options:
      name: http2tls12
    secretName: wildcard-hyvel-certificate-secret
    domains:
      - main: cache.hyvel.eu
  entryPoints:
    - websecure
  routes:
    - match: Host(`cache.hyvel.eu`)
      middlewares:
        - name: security-headers
          namespace: tproxy
        - name: hide-h3-header
          namespace: tproxy
      kind: Rule
      services:
        - kind: Service
          name: app
          port: 7771
