apiVersion: gateway.networking.k8s.io/v1
kind: TLSRoute
metadata:
  name: app
  namespace: tproxy
spec:
  parentRefs:
    - name: main-gw
      namespace: kgateway
      sectionName: tls-mimic-2
  hostnames:
    - "www.klick.ee"
  rules:
    - backendRefs:
      - name: app
        port: 7770

---

apiVersion: gateway.kgateway.dev/v1alpha1
kind: BackendConfigPolicy
metadata:
  name: app-pp
  namespace: tproxy
spec:
  targetRefs:
  - group: ""
    kind: Service
    name: app
  upstreamProxyProtocol:
    version: V2