apiVersion: v1
kind: Secret
metadata:
    name: app-1
    namespace: tproxy
stringData:
    config.toml: ENC[AES256_GCM,data:4Dx7OkeCMJFcwmUCY1qzC1c2qlIV6UwR/qo84450YDIjK1m7lJJbF6W+sgsaUyikpFtMW1RrZhqPjzlReLul9p963zWchJWP2m1vAxwrlWIkTOIt5POCZyfEHtlH3db6qxPg5efPVNBzkPBAqanchFvxK3S/FG3+mrsxNEEOHrIiAN5YYdVQ4yzvyHMYGgqvKJeLd5UJAKK4SR41NJ7/yHEC0QtK9xcpYaXk5LLI+TFGoc2D+MqLjfKaxwxZe0DXWvGtntKuASFvSRzJNhpEO6seMx4VzLmCMeqFWXiqmsP3bs1Raw/khsghQYiMSZRzDEYKKEGJJwoIHooum9hkVAH0wY6pXJtKrENv7eIzbEBwLa49hrFThOCpJdIwYNJRiQBXiCPTKyppl+adqLTduUD0KO29XSW1IUiTFERjJ59Hh6XfllPC/6uFnwTd/GMZmsFnmx6II4KXMLRta58eVKAITnSCJY/Jd2kC/9t/7+98J4TylQ+sezIdzgA/LfU71UkpoygKHiQNW4dYFzY2Qgcdt/jNKgub1tjPtsSJvRxEfv4asVUibqNXBq/krNHtA3h6L2tbp0Yvcs0HTY9rXoYvHMa/uB7XEtMnyDeDh9T0XQMpxWA56gQAiT+pLMo7AfvcmYDoBVLXfBjXd/juTKhrbtR3Hr7MhGT7EZNV3IMUbd0YEhl3+5R2yWtHnerKNgNu9m41CZo0QklXM0Tu0OibruWkBjcvNlvCHQ0om5fhzgAShqpDSyuCvCgWfeSCqGUfJSzfDSn5ciOBKsanDIiWPisQhF8ZiBYnbUHvNyVPO976NPoLAz/mSF1CgDUjcprdJuUOiRR+kd3N3V7JP7KBAI0Nn9jxpqd8Zil60jRTMccQ84k6TxL2Asqky4cCX/ucA2pe,iv:0VA4lKiQY1EJoVppdEmoV2oWIlwJ5c9d14/XqZSf7GI=,tag:esq1oJTNXLDwYdXg8fukzA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQkxyM1N6YlJRRzF0cXht
            VGtQNytjZm11UDhabjV4TlNKVld4T2xuL1hRCm5UR0FJNFRjZkpmclVHVnk0dFdv
            cjRBeWFIN0NEMzRLeDFvRmFHVjVUa1kKLS0tIENoUGNIU2dpb0tzd2ptL3d2S0kw
            SWdlTUx5b3AzQVlJOWJjTS82ZEZzR1EKcN/bgIHv60iqDA6n2xs/zSOV67V/JaY5
            FN3I4rR7kWRJZhz3uuuTZ3/1njsRUCbOr7vzJRjGEhkJcXLnkBXsTg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1na9sc4yaxzdvt5jqpq99q3umg2qkhsv3use7lgej6lw46wz8sgrspg7a2h
    encrypted_regex: ^(data|stringData|email|token_id|token_secret|client-certificate-data|client-key-data|certificate-authority-data)$
    lastmodified: "2026-07-09T08:24:05Z"
    mac: ENC[AES256_GCM,data:Z/fSG+zuzOJJUSunVMArWTSwE6LEJqwHST8dcII+PFM8+StGOks6SV0xY32/nvaeMVikIpZmeI8b2b5+KeSqgP1ZJV2vOFf0aSRYgzgytRlRGdTUWIztqXSckI93/XoR1utBcGCAa4WHCaVY/pqzgztHFllkjBzOAPNljGp019o=,iv:sXJVEgovvqBEg1JBXWiucxqiK6vipfZhlsYhVvV9odI=,tag:Lejd2cF1O1+5ZEOR5LOiMA==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: app-2
    namespace: tproxy
stringData:
    config.toml: ENC[AES256_GCM,data:XehkAp5QMMYTKIbyad0TrR0ADQpV6Akc5np+XFRRuqb/a1vO9w53ttiKTXzHzuqB3AkcXDmftp9B3cdO1KL9kEYmMcoH6pEFkRqda/V9dTc6kYT9XglRBtcN7jHBqHmU9wjTC8d5JotJYFXtJssNvM7BIs2jBJD/04/y9SaO8glczOcpZcb85Z8vDzXK5vkKE6M3vF/gmGvIOd8UpWo5Zd3P+8Ma/pz2PcmWk7OT9S+ilFe8uB012923HIzOeUzPtdcoS5GS4LJ2+bgFSBrBlOp3rPXcpjfrUtdk27qC/K74cmmJdNxLeVU2unzNDyAfodCSCZT+Zoa11LKBeeYbIv1h6R4dMaFTkhPWpaBKIz2XU9fHnZAC5rzEN3r5e5nCPjj3HRF3nXnOie8FUCra2euvsTcEpj2U+jOWhU4Yu2Yg8+k+s2x+ffllAXsa/6LsaUu33RCFtmctfVZoMPAT2txcekBPIrTZhJYVkTqUDMFREmEtqaJlRWQjpLHVCucW71U7+mbZlUPt+jwy3o2O/XnRM5fn5N7/6UUvpYMy2XGqZ4kt/EKSTqYlSzPtW4wtZa4Olpf98UguoTM5Wz0SGO/hCeBdTs6iB7xADHn7Ov5A/x5js8SWFodSDdka2qRk8vIRe6JUWP3QyodJBpSdtOSKHH6Exyh32QIaAqVaqXTasEHmJLull3tDgjGvwO95F1R9j8EWvRwq/xKGWQTvWa1n9lqvZSZT8RoZ7nFdLpi5BTHcJLVTM8dk0hkFOeKvX0XnTQCT4aZe//8hu3ToEHvmybINF2QVAM1KOyNWjGwtWDYAfE4yhu00XGlLlfDZwrwzzXU7WJQ7I+O15QkByLHaiVxOd6xvnYeMlb6o,iv:WVce7JTTvy6HN2AwTZn2ue7V+nX3kBsC0BLxPRXW6cc=,tag:ELMGyN6lZCRN2k1tNmJqqQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQkxyM1N6YlJRRzF0cXht
            VGtQNytjZm11UDhabjV4TlNKVld4T2xuL1hRCm5UR0FJNFRjZkpmclVHVnk0dFdv
            cjRBeWFIN0NEMzRLeDFvRmFHVjVUa1kKLS0tIENoUGNIU2dpb0tzd2ptL3d2S0kw
            SWdlTUx5b3AzQVlJOWJjTS82ZEZzR1EKcN/bgIHv60iqDA6n2xs/zSOV67V/JaY5
            FN3I4rR7kWRJZhz3uuuTZ3/1njsRUCbOr7vzJRjGEhkJcXLnkBXsTg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1na9sc4yaxzdvt5jqpq99q3umg2qkhsv3use7lgej6lw46wz8sgrspg7a2h
    encrypted_regex: ^(data|stringData|email|token_id|token_secret|client-certificate-data|client-key-data|certificate-authority-data)$
    lastmodified: "2026-07-09T08:24:05Z"
    mac: ENC[AES256_GCM,data:Z/fSG+zuzOJJUSunVMArWTSwE6LEJqwHST8dcII+PFM8+StGOks6SV0xY32/nvaeMVikIpZmeI8b2b5+KeSqgP1ZJV2vOFf0aSRYgzgytRlRGdTUWIztqXSckI93/XoR1utBcGCAa4WHCaVY/pqzgztHFllkjBzOAPNljGp019o=,iv:sXJVEgovvqBEg1JBXWiucxqiK6vipfZhlsYhVvV9odI=,tag:Lejd2cF1O1+5ZEOR5LOiMA==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: app-3
    namespace: tproxy
stringData:
    config.toml: ENC[AES256_GCM,data:62nD1s2X9E4i+FcJYTFlQLEvI/K3u4IqKnmKzgW5O4/DwaeyNZOlLo1nEOGHkS8lmHKKXDIpAl/lo7LB8EROUAqmqZOU79t1onh3abjS92UxAtNK14rI6d+UV6DnYioi/9NmDYopSz+1x6adle3jhtQ0okHfyBvQq32a0esnhTgLnsU4v/dWo4krkxITEzBBCZv8DLceaMX1bYznh+Md3HysD2pLZ3NEPzjM6HZXAzbJ0mcbT79WPh8yH0FZLzcof17GItPgMdvV58bFo9pnudjqIoAZW4IkN/bn6YSg6BvrTjdQyLfJAw6QaadSCz+vQswE26+eqV5FWuFLeWy6Hlu0Hn7trdQTI+r7nJgjsUVZE9Kli2YPX89Gx9zFcrOH41AYPtGEJiKBosefyw97AdmDOz8iQ9UHtGyqf0/odK/8cpW6uMJP3zV84vDbkZRXaOgN4rNeGCTAkiRWYQTnNr3uKXAavBizAose3YGQL9+MqbjKtU/QcqYgAHM9raWSajWIDLO57QLRbWF/ycJoG3jtLJKdmXkk1rujLsjBuAekhswJmcJOp+3pSHXsNy/Q1nJEdM9WYqsg63J8O5zO0wKbUTNJ/fFa7u4kfhXGtjVptGtnWjaGoKHKnamJfPnbQOggsgIVPwRoKYK1iEjIGyB+5TYXFCXXMz4Xg0C0KrQCv5VaxfUj51DYCQE2CmZLWErn3VadA8L23MoGm+A/zxgSHmr9uw0pw25h3KXiW0RV6a/cqRwlU8Mns2sRIIRiOuu9RUsInQ4qU31WKc98/yLvBfseDuOm+oreRb7gtyhDBcxtrE96yoaPnkMT0H6jFvH3nRunB6hfTY/4VSJyLJ2Xqku/Ii1AYOPXPHhVxDqA,iv:m6kdb5fr/uX5k+kM4WwRFZw6qoo+IhUAVqJeFb5BiA0=,tag:FHzwdJK/YQdgdhYfEH6PFA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQkxyM1N6YlJRRzF0cXht
            VGtQNytjZm11UDhabjV4TlNKVld4T2xuL1hRCm5UR0FJNFRjZkpmclVHVnk0dFdv
            cjRBeWFIN0NEMzRLeDFvRmFHVjVUa1kKLS0tIENoUGNIU2dpb0tzd2ptL3d2S0kw
            SWdlTUx5b3AzQVlJOWJjTS82ZEZzR1EKcN/bgIHv60iqDA6n2xs/zSOV67V/JaY5
            FN3I4rR7kWRJZhz3uuuTZ3/1njsRUCbOr7vzJRjGEhkJcXLnkBXsTg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1na9sc4yaxzdvt5jqpq99q3umg2qkhsv3use7lgej6lw46wz8sgrspg7a2h
    encrypted_regex: ^(data|stringData|email|token_id|token_secret|client-certificate-data|client-key-data|certificate-authority-data)$
    lastmodified: "2026-07-09T08:24:05Z"
    mac: ENC[AES256_GCM,data:Z/fSG+zuzOJJUSunVMArWTSwE6LEJqwHST8dcII+PFM8+StGOks6SV0xY32/nvaeMVikIpZmeI8b2b5+KeSqgP1ZJV2vOFf0aSRYgzgytRlRGdTUWIztqXSckI93/XoR1utBcGCAa4WHCaVY/pqzgztHFllkjBzOAPNljGp019o=,iv:sXJVEgovvqBEg1JBXWiucxqiK6vipfZhlsYhVvV9odI=,tag:Lejd2cF1O1+5ZEOR5LOiMA==,type:str]
    version: 3.13.1
