apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: tproxy
  labels:
    app.kubernetes.io/name: tproxy
    app.kubernetes.io/component: app
spec:
  selector:
    app.kubernetes.io/name: tproxy
    app.kubernetes.io/component: app
  ports:
    - name: app-1
      protocol: TCP
      port: 7770
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: app-lb
  namespace: tproxy
  labels:
    app.kubernetes.io/name: tproxy
    app.kubernetes.io/component: app
spec:
  selector:
    app.kubernetes.io/name: tproxy
    app.kubernetes.io/component: app
  ports:
    - name: app-2
      protocol: TCP
      port: 7771
    - name: app-3
      protocol: TCP
      port: 7772
  loadBalancerIP: 192.168.200.13
  type: LoadBalancer